# Generated by Django 4.1.6 on 2023-06-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
