# Generated by Django 4.1.6 on 2023-06-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_alter_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
